openapi: 3.0.0
info:
  title: Insight IQ Auth API
  version: 1.0.0
  description: Authentication-related APIs including Signup and Login.

servers:
  - url: http://localhost:8080/api/v1

paths:
  /auth/signup:
    post:
      summary: Register a new user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                accountType:
                  type: string
                  enum: [Student, Mentor]
                imageUrl:
                  type: string
                  format: uri
                active:
                  type: boolean
              required: [fullName, email, password]
      responses:
        200:
          description: User registered successfully
        401:
          description: User already registered
        403:
          description: Missing required fields

  /auth/login:
    post:
      summary: Login user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required: [email, password]
      responses:
        200:
          description: Login successful with JWT token
        401:
          description: Invalid credentials
        403:
          description: Missing required fields

  /mentors:
    get:
      summary: Get all mentors with their details
      tags:
        - Mentors
      responses:
        '200':
          description: A list of mentor users
        '500':
          description: Server error
          